### ISSUE TITLE
Creation of Catalogue and System Requirements Document

### ISSUE THREAD

**Issue by RnsC-08** [TIS2024-FMFI/backup#4]
The Catalogue of Requirements and the System Requirements document were successfully created, defining the technical details of the Backup System and we separated the work of the group.

**Comment by pavelpetrovic** [comment]
The issues are here to write all the relevant information about the issue in the communication thread of the issue. For example, here I would expect to find a link to the latest version of the document you have produced, but it's just plain empty.
Remember, the ONLY communication platform you should use to work on the project should be Github issues.

**Comment by RnsC-08** [comment]
The System Requirements Document is saved in the Documents branch.

First Draft: [FirstSRS.pdf](https://github.com/user-attachments/files/18361356/FirstSRS.pdf)

Final Version: [Software Requirements Specification 2.pdf](https://github.com/user-attachments/files/18361246/Software.Requirements.Specification.2.pdf)

The final version includes all the changes and feedback. Details about the changes and how we divided the work can be found in [Meeting 5 ‐ 07/11/2024](https://github.com/TIS2024-FMFI/backup/wiki/Meeting-5-%E2%80%90-07-11-2024) also for the first Draft on the [Meeting ‐ 08/10/2024](https://github.com/TIS2024-FMFI/backup/wiki/Meeting-%E2%80%90-08-10-2024)

> The issues are here to write all the relevant information about the issue in the communication thread of the issue. For example, here I would expect to find a link to the latest version of the document you have produced, but it's just plain empty. Remember, the ONLY communication platform you should use to work on the project should be Github issues.
